language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: FcsrfQ0ZzlwIGLB0bz//S9A8BkDopi/W/QWRcrXzUb1uIou+2TQoZvm0W3f+GXXLfuogYOl8rIGYKZWPUIZkdGc/gYA5EAHeTIVCQzCrfN4S1ylueJY+u1kQh2YWPvkoSFWNOG8kBmvob3H2Zpix4Vu7LbUFqA3MVR5vB7nLr2wvrvaW7n75mdNukGz23n3G5QyZQJgg67oqV69/BScQAS8kXfwJmm+u7HXpbC1tVdfWk7zmTg+y5WoaZcN2nNghJCtzWOEkmmd16n3lpb2r3Xl+n4lKM772bv7jtzkXu+9koh2PTmicuIRJdG8sTqYHNeoZHcGFnipYo5c+OWV2cYnqnXDomnCcdDJF3/3jRIWn1pPjfWiK2NgB0W/stlC3kNagc3uW+Sp6INrI1cCOZKGREPbD6XgBoTaSh9qml6FFUfq8u5qgzKH4A4kqYJRfLPfIYy7YxihhPx4/0h9WWBTNQBcLmQq1t7YvGXzHLlDx1J5zoB+imzELU5FXghYuHG113mTqPuxnGt4v0zbn8aIKhnMENwGP/cWkFZ1sCfDsD09dBgmXNhZqq9j4YaXrSVZK5tEk8s/bsWSOqrCORgAwOvF5GLmH0qfOdX6CD8Qp8L1fX+BxrIo9ereoWaaIqk9+J5nnmzF/APyfSNhh1TjCLsBQvE0wC1FCjjfvntU=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xlr-nuget-trigger-plugin
    all_branches: true
    tags: true
notifications:
  hipchat:
    rooms:
      secure: dldBcDS/lR+4AVYCWxWZ1g9hohq4npXK4aMBZM1EZod5jeVYNyEeotGKgT4SgxhcQSYKr/z14kAqeH8zo7w/aEC/c86bnI4o5sVQ7AGcRVkEiHuDinBqhxmH+g3WM+mT3UNr8MnfJ37zSqSx4I5rx9C9In3jJ/7fKxT11IKhSDNZ/4DFY+CGgbRnl5gAy7k/XidT0KEACHUjXBDZXMg6SIr7TGXyxFUufhREdtilc4g2RDCBEqP/BBUfRgXlR6QRgYmPwc5yzG5FZA+/P1VLRr2JkAwhrycLWp+3Sf/bKTTHEG2bm4BDzSzb10FwU3wg9eXGiOvjjJ8KLwWi7+IkzyagNbgBi7SEtzrmQgVOtX/2nmvZgEz1b6cGicMFXCo6NXHAFR7IsKQARtHQ8Yos0dXXczXFW0CQkddWrhUDIOq2SyZrgKdsLOWIpJLK62//wpIIr44LIjZcMaO6GbdjkKZ0XYhuKN4vfPpzlninrEEzomud6SV0BVGm0av1n/2tZgyd5zee79aIhFEwNXERdL52mFO6Hd76ayCBNDjM+NMpVAABCvLNHDmp2iXd5VH4AnIKWtoaTs9oaraYfXRSWIyg9CymUws9uQ46K6DPVGGxZYjWgE4e7P6Pql5Fqh8FL14Y9/6dlMnRfBhuLfMGDrlc1pptMmVUxKExMfgmFn8=
