language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: FcsrfQ0ZzlwIGLB0bz//S9A8BkDopi/W/QWRcrXzUb1uIou+2TQoZvm0W3f+GXXLfuogYOl8rIGYKZWPUIZkdGc/gYA5EAHeTIVCQzCrfN4S1ylueJY+u1kQh2YWPvkoSFWNOG8kBmvob3H2Zpix4Vu7LbUFqA3MVR5vB7nLr2wvrvaW7n75mdNukGz23n3G5QyZQJgg67oqV69/BScQAS8kXfwJmm+u7HXpbC1tVdfWk7zmTg+y5WoaZcN2nNghJCtzWOEkmmd16n3lpb2r3Xl+n4lKM772bv7jtzkXu+9koh2PTmicuIRJdG8sTqYHNeoZHcGFnipYo5c+OWV2cYnqnXDomnCcdDJF3/3jRIWn1pPjfWiK2NgB0W/stlC3kNagc3uW+Sp6INrI1cCOZKGREPbD6XgBoTaSh9qml6FFUfq8u5qgzKH4A4kqYJRfLPfIYy7YxihhPx4/0h9WWBTNQBcLmQq1t7YvGXzHLlDx1J5zoB+imzELU5FXghYuHG113mTqPuxnGt4v0zbn8aIKhnMENwGP/cWkFZ1sCfDsD09dBgmXNhZqq9j4YaXrSVZK5tEk8s/bsWSOqrCORgAwOvF5GLmH0qfOdX6CD8Qp8L1fX+BxrIo9ereoWaaIqk9+J5nnmzF/APyfSNhh1TjCLsBQvE0wC1FCjjfvntU=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xlr-nuget-trigger-plugin
    all_branches: true
    tags: true
notifications:
  slack:
    secure: LBPoGxQZTotU5G/d8J3zCd6XO49xtCCncYfDwgzSg2OFhDAFIFHTLVFzx1wdf25F76DO9RE+c6dYBR0FRzXy3UO6fcqdZNgJWbAd+6WEjtIHiJ1ZFxDXUVCEnLu3DvDm3vD60OxrpwTiCFphSWAe+6tZ1g77DemxRjvDixJfDq1gsQEv3pB/pwz+a6BDnYlud2z2A6aA8iQkrJQ6lQQkBmDfKmGqul1ela0w3ovrWIrS+ornuZtr9PZ8eyUsjhO+Qpin8M4nWrAdXaE7SgQMVp1f3MISrVJ+yJaGB+vtcHwT6EjdVRobheIYKd/TpjykmLiaO7BmOmHrHahkH9K2AuQ+v+HulRG2pP+hsrq/KdTez43jC+1QeidTr8hfHC2UhDFWcoyualY4ckq2zkbJH3iSomDeyDF8KnDa7dn5Zh2s96eoxj7h8UUVFJ5h+gZLrjkesfBurmo8aGRmyoWEdZv/MwwoHgkdQszWXP9u0pyvc1rPMKm4nwmvee5Il4bxGVD1J+8Slszsl3sKK5a/4GUthw04VTL3OFcgjg3qrOR77wMBy8MC/3Sy9z+fCR3v4G4esprT3hHDU8VIdaT+IbxB0oYKnJRwBW5Ic5hSWrnCybLnGvZgWCZavaLXHFvDIIRfUpkUt/dKjwDUbBchR/iVHLV9NLNZSSf8/T5mLgs=
