language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: BV7HOFc+7ZlltMq1cMLMQ6QNQjd+KQSNiDpBnHEeuPJDMq+l+H9BukIsRLZSd79aUjU7n/Dk1emOI9v7ImWsNUKrc6sfFJx8u/8sgG0eLjbrHgG/ORzvZSKDgjA42ufbSCfScMTgRP9FsAn130JUhTjqJVb9B0RGGKDCLZPbZtRXscYDMxLyfbNEd4GIsKlmiyibUhPjRClpEW7HCALpLwYxA/Qc/+H90YYyNZrC6oEY51eesGiMZOZDY3O3h0dqWRceywLZhqXUTYH+h75oVdlU5hqsTIYwgtLx8ZCAJs/iZleb+G4pFEcAJj3lKo81JCClGnAWJVdN1LJczKjWD9u4Zwk2TgpE964SliA23QsKJDAFjW3bS/UxRwok9R2gH/nbo+YbLiDon6KbHp0g3PJNFXuBCGEiy3dCQLAWdW7g2at/c89oJvTNC40hDDfyCX7pYXnVoS9GVd92SGCA8qAyC2+CopeM3zIYexh4FZQiO4qyLf7D1l/27mrLIRKDbWupP7A4klIjoY7F++CTWWmuIc3kVMTdZT+nfqqxBr1ySLaOp+IwbxqukuXnBKtO36fTA059Cvn1j5bwWoVdMPMyMb6hzShYElF03wrk34NjcYd/jSFB54cu6sGoMGg26E+O3wzVt8y+2XfGYEzY9BaQ3WPtMpdA+iFwCW1rxGY=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xlr-nuget-trigger-plugin
    all_branches: true
    tags: true
notifications:
  hipchat:
    rooms:
      secure: dldBcDS/lR+4AVYCWxWZ1g9hohq4npXK4aMBZM1EZod5jeVYNyEeotGKgT4SgxhcQSYKr/z14kAqeH8zo7w/aEC/c86bnI4o5sVQ7AGcRVkEiHuDinBqhxmH+g3WM+mT3UNr8MnfJ37zSqSx4I5rx9C9In3jJ/7fKxT11IKhSDNZ/4DFY+CGgbRnl5gAy7k/XidT0KEACHUjXBDZXMg6SIr7TGXyxFUufhREdtilc4g2RDCBEqP/BBUfRgXlR6QRgYmPwc5yzG5FZA+/P1VLRr2JkAwhrycLWp+3Sf/bKTTHEG2bm4BDzSzb10FwU3wg9eXGiOvjjJ8KLwWi7+IkzyagNbgBi7SEtzrmQgVOtX/2nmvZgEz1b6cGicMFXCo6NXHAFR7IsKQARtHQ8Yos0dXXczXFW0CQkddWrhUDIOq2SyZrgKdsLOWIpJLK62//wpIIr44LIjZcMaO6GbdjkKZ0XYhuKN4vfPpzlninrEEzomud6SV0BVGm0av1n/2tZgyd5zee79aIhFEwNXERdL52mFO6Hd76ayCBNDjM+NMpVAABCvLNHDmp2iXd5VH4AnIKWtoaTs9oaraYfXRSWIyg9CymUws9uQ46K6DPVGGxZYjWgE4e7P6Pql5Fqh8FL14Y9/6dlMnRfBhuLfMGDrlc1pptMmVUxKExMfgmFn8=
